"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var email_controller_1 = require("./email.controller");
var router = (0, express_1.Router)();
router.get("/", email_controller_1.EmailController.getEmails);
router.post("/", email_controller_1.EmailController.createEmail);
router.get("/:id", email_controller_1.EmailController.getEmail);
router.delete("/:id", email_controller_1.EmailController.deleteEmail);
router.delete("/", email_controller_1.EmailController.deleteAllEmails);
exports.default = router;
